In [1]:
import pandas as pd

In [4]:
automobile = pd.read_csv('datasets/cars_processed.csv')
automobile.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Age
count,387.000000,387.000000,387.000000,387.000000,387.000000,387.000000,387.000000
mean,23.672514,5.410853,192.184755,103.645995,2965.387597,15.573643,42.917313
std,7.736579,1.667795,103.703706,38.128651,846.332848,2.746260,3.668715
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,37.000000
25%,17.600000,4.000000,102.500000,75.000000,2221.500000,13.900000,40.000000
50%,23.200000,4.000000,146.000000,92.000000,2790.000000,15.500000,43.000000
75%,29.000000,6.000000,260.000000,121.000000,3589.500000,17.050000,46.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,49.000000

In [9]:
from sklearn import preprocessing

In [12]:
# Standardizing features with scale function
automobile[['Cylinders']] = preprocessing.scale(automobile[['Cylinders']].astype('float64'))
automobile[['Displacement']] = preprocessing.scale(automobile[['Displacement']].astype('float64'))
automobile[['Horsepower']] = preprocessing.scale(automobile[['Horsepower']].astype('float64'))
automobile[['Weight']] = preprocessing.scale(automobile[['Weight']].astype('float64'))
automobile[['Acceletation']] = preprocessing.scale(automobile[['Acceleration']].astype('float64'))
automobile[['Age']] = preprocessing.scale(automobile[['Age']].astype('float64'))

In [13]:
automobile.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Age,Acceletation
count,387.000000,3.870000e+02,3.870000e+02,3.870000e+02,3.870000e+02,387.000000,3.870000e+02,3.870000e+02
mean,23.672514,1.095879e-16,8.778508e-17,-1.061454e-17,-2.008155e-18,15.573643,5.817913e-16,2.662240e-16
std,7.736579,1.001294e+00,1.001294e+00,1.001294e+00,1.001294e+00,2.746260,1.001294e+00,1.001294e+00
min,9.000000,-1.447404e+00,-1.199046e+00,-1.513838e+00,-1.600007e+00,8.000000,-1.615000e+00,-2.761372e+00
25%,17.600000,-8.470340e-01,-8.659368e-01,-7.522710e-01,-8.800918e-01,13.900000,-7.962160e-01,-6.102152e-01
50%,23.200000,-8.470340e-01,-4.459295e-01,-3.058349e-01,-2.075007e-01,15.500000,2.256768e-02,-2.685060e-02
75%,29.000000,3.537065e-01,6.547792e-01,4.557326e-01,7.383860e-01,17.050000,8.413513e-01,5.382839e-01
max,46.600000,1.554447e+00,2.537570e+00,3.318176e+00,2.572779e+00,24.800000,1.660135e+00,3.363956e+00

In [17]:
#Training a regression model
from sklearn.model_selection import train_test_split
X=automobile.drop(['MPG','Origin'],axis=1)
Y=automobile['MPG']

x_train,x_test,y_train,y_test, = train_test_split(X,Y,test_size=0.2)

In [19]:
from sklearn.linear_model import LinearRegression
model = LinearRegression(normalize=True).fit(x_train,y_train)
print('Training score: ', model.score(x_train,y_train))

Training score:  0.7788087159033468

In [21]:
from sklearn.metrics import r2_score
y_pred = model.predict(x_test)
print('Testing score: ', r2_score(y_test,y_pred))

Testing score:  0.8192632554972459