In [25]:
import pandas as pd
import numpy as np
# from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [26]:
diabetes = pd.read_csv('datasets/diabetes_processed_incomplete_1.csv')
# diabetes.head(10)

In [28]:
diabetes_features = diabetes.drop('Outcome',axis=1)
diabetes_label = diabetes[['Outcome']]
imp = IterativeImputer(max_iter=10000,random_state=0)
imp.fit(diabetes_features)

IterativeImputer(max_iter=10000, random_state=0)

In [30]:
diabetes_features_arr = imp.transform(diabetes_features)
diabetes_features = pd.DataFrame(diabetes_features_arr, columns=diabetes_features.columns)
diabetes_features.head()

,Unnamed: 0,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,SkinTickness
0,0.0,6.0,148.0,72.0,35.0,219.313437,33.6,0.627,50.0,35.0
1,1.0,1.0,85.0,66.0,29.0,71.819111,26.6,0.351,31.0,29.0
2,2.0,8.0,183.0,64.0,32.0,272.896497,23.3,0.672,32.0,32.0
3,3.0,1.0,89.0,66.0,23.0,94.000000,28.1,0.167,21.0,23.0
4,4.0,0.0,137.0,40.0,35.0,168.000000,43.1,2.288,33.0,35.0

In [33]:
# Removing the unnamed column
diabetes_features = diabetes_features.iloc[: , 1:]
diabetes_features.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,SkinTickness
0,148.0,72.0,35.0,219.313437,33.6,0.627,50.0,35.0
1,85.0,66.0,29.0,71.819111,26.6,0.351,31.0,29.0
2,183.0,64.0,32.0,272.896497,23.3,0.672,32.0,32.0
3,89.0,66.0,23.0,94.000000,28.1,0.167,21.0,23.0
4,137.0,40.0,35.0,168.000000,43.1,2.288,33.0,35.0

In [34]:
diabetes = pd.concat([diabetes_features,diabetes_label],axis=1)
diabetes.head()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,SkinTickness,Outcome
0,148.0,72.0,35.0,219.313437,33.6,0.627,50.0,35.0,1
1,85.0,66.0,29.0,71.819111,26.6,0.351,31.0,29.0,0
2,183.0,64.0,32.0,272.896497,23.3,0.672,32.0,32.0,1
3,89.0,66.0,23.0,94.000000,28.1,0.167,21.0,23.0,0
4,137.0,40.0,35.0,168.000000,43.1,2.288,33.0,35.0,1

In [36]:
diabetes.to_csv('datasets/diabetes_processed_1.csv', index=False)